import React from 'react';
import GlassCard from './GlassCard';
import Button from './Button';
import jsPDF from 'jspdf';
import 'jspdf-autotable';

const ResultCard = ({ prediction, probability, riskLevel, extras = [] }) => {
    const isHighRisk = prediction === 1;
    const probPercent = (probability * 100).toFixed(1);

    const generatePDF = () => {
        const doc = new jsPDF();
        const date = new Date().toLocaleDateString();
        const patientName = extras.find(e => e.label === 'Patient' || e.label === 'Patient Name')?.value || 'Anonymous';

        // Title
        doc.setFontSize(20);
        doc.setTextColor(33, 37, 41);
        doc.text('Health Risk Assessment Report', 14, 22);

        // Header Info
        doc.setFontSize(11);
        doc.setTextColor(100, 100, 100);
        doc.text(`Date: ${date}`, 14, 32);
        doc.text(`Patient: ${patientName}`, 14, 38);

        // Results Section
        doc.setFontSize(14);
        doc.setTextColor(33, 37, 41);
        doc.text('Prediction Results', 14, 50);

        doc.setFontSize(12);
        if (isHighRisk) {
            doc.setTextColor(220, 53, 69); // Red for high risk
            doc.text(`Risk Level: ${riskLevel}`, 14, 60);
        } else {
            doc.setTextColor(40, 167, 69); // Green for low risk
            doc.text(`Risk Level: ${riskLevel}`, 14, 60);
        }

        doc.setTextColor(33, 37, 41);
        doc.text(`Confidence Score: ${probPercent}%`, 14, 68);

        // Summary Text
        doc.setFontSize(10);
        doc.setTextColor(80, 80, 80);
        const summaryText = isHighRisk
            ? "The model has detected patterns consistent with a high risk profile. It is strongly recommended to consult a healthcare professional for a formal diagnosis."
            : "The parameters provided indicate a low risk profile. Continue to maintain a healthy lifestyle and regular check-ups.";
        const splitText = doc.splitTextToSize(summaryText, 180);
        doc.text(splitText, 14, 78);

        // Parameters Table
        if (extras && extras.length > 0) {
            const tableData = extras.map(item => [item.label, item.value]);

            doc.autoTable({
                startY: 95,
                head: [['Parameter', 'Value']],
                body: tableData,
                theme: 'striped',
                headStyles: { fillColor: [41, 128, 185] },
                margin: { left: 14, right: 14 }
            });
        }

        // Footer
        const pageCount = doc.internal.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.setTextColor(150, 150, 150);
            const footerText = 'This report is generated by an AI model and should not replace professional medical advice.';
            doc.text(footerText, 14, doc.internal.pageSize.height - 10);
        }

        doc.save(`${patientName.replace(/\s+/g, '_')}_Risk_Report.pdf`);
    };

    return (
        <GlassCard className="mt-8 animate-fade-in-up border-t-4" strong={true} style={{ borderTopColor: isHighRisk ? '#ef4444' : '#22c55e' }}>
            <h3 className="text-xl font-bold mb-4 text-slate-800 border-b pb-2">Prediction Results</h3>

            <div className="flex flex-col md:flex-row items-center justify-between gap-6 py-4">
                <div className="flex-1 text-center md:text-left">
                    <p className="text-slate-500 text-sm mb-1 font-medium">Status Classification</p>
                    <div className="flex items-center justify-center md:justify-start gap-3 mb-2">
                        <span className={`inline-flex items-center justify-center w-3 h-3 rounded-full ${isHighRisk ? 'bg-danger animate-pulse shadow-sm shadow-danger/50' : 'bg-primary shadow-sm shadow-primary/50'}`}></span>
                        <p className={`text-3xl font-bold ${isHighRisk ? 'text-danger' : 'text-primary'}`}>
                            {riskLevel}
                        </p>
                    </div>

                    <p className="text-slate-600 mt-4 leading-relaxed font-medium">
                        {isHighRisk
                            ? "The model has detected patterns consistent with a high risk profile. It is strongly recommended to consult a healthcare professional for a formal diagnosis."
                            : "The parameters provided indicate a low risk profile. Continue to maintain a healthy lifestyle and regular check-ups."}
                    </p>
                </div>

                <div className="bg-slate-50 p-6 rounded-xl border border-borderLight w-full md:w-auto text-center min-w-[200px] flex flex-col justify-center items-center shadow-sm">
                    <p className="text-slate-500 text-sm mb-2 font-medium">Confidence Score</p>
                    <p className="text-5xl font-black text-slate-800">{probPercent}%</p>

                    {/* Progress Bar Indicator */}
                    <div className="w-full bg-slate-200 rounded-full h-2.5 mt-4 overflow-hidden">
                        <div className={`h-2.5 rounded-full ${isHighRisk ? 'bg-danger' : 'bg-primary'}`} style={{ width: `${probPercent}%` }}></div>
                    </div>
                </div>
            </div>

            <div className="mt-6 flex justify-center border-t border-borderLight pt-6">
                <Button onClick={generatePDF} variant="secondary" className="flex items-center gap-2 max-w-xs">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                        <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path>
                        <polyline points="7 10 12 15 17 10"></polyline>
                        <line x1="12" y1="15" x2="12" y2="3"></line>
                    </svg>
                    Download PDF Report
                </Button>
            </div>
        </GlassCard>
    );
};

export default ResultCard;
